### ISSUE TITLE
[Suggestion] Openplanet UI scaling slider 

### ISSUE THREAD

**Issue by bastiHST90** [openplanet-nl/openplanet-issues#123]
Openplanets UI (+plugins) get very big with lower resolutions, while the game UI looks completely normal. A slider to scale the UI of Openplanet + Plugins would be a super nice feature.

**Comment by codecat** [comment]
Technically possible right now, but since fonts aren't rendered as vectors, this will make scaled-up fonts blurry (and scaled-down fonts pixelated). So I haven't implemented it yet.

Something like [this pull request](https://github.com/ocornut/imgui/pull/4056) or [this one](https://github.com/ocornut/imgui/pull/3471) would be very nice to have before this can be properly implemented.

**Comment by bastiHST90** [comment]
Sounds good. I wouldn't mind to test this right now. maybe the fonts wouldn't be too bad in my case. haha

But a option would be so nice.

**Comment by codecat** [comment]
You can try this out right now, although it's more of a debug feature:

Developer -> Debug -> GUI Demo -> Configuration -> Style -> Fonts -> "global scale"

![image](https://user-images.githubusercontent.com/136534/174435160-a33e86c4-fff4-4798-bed3-260ecc2f5e0c.png)

**Comment by bastiHST90** [comment]
I tried it and I like it actually.

Dashboard doesn't scale, because I can scale it myself.
That's great on one hand, on the other, not so much, when I use the same device with sometimes different resolutions, I have to scale more things at once and I'm to lazy for that. haha. it's probably just me with this usecase.

**Comment by codecat** [comment]
Well, Openplanet could make use of Windows' current display scaling values too which might solve your use case as well.

This would also have other implications on certain plugins, for example Better Chat might react kinda weird to an increased global scale 🤔

**Comment by bastiHST90** [comment]
I don't know about that, my usecase is a steam deck with Linux as you might know from discord. 😅

I know what could maybe be cool.

When you implement global scaling, maybe give the option to save it, so users can quickly switch between different resolutions/scalings.


That got me thinking... maybe give users the option to save the current layout of all plugins onscreen (+scaling when implemented) 

So than I could have maybe 2 (or more) saves for native resolution + arbitrary resolutions.

Just a thought 😅

**Comment by fentras** [comment]
Another workaround would be to render whole _ImGui_ at a lower resolution. It'll fix janky fonts but will make everything blurry.

#### 1600x900 (native)
![1600x900](https://user-images.githubusercontent.com/26721650/177040360-bc62800a-c61d-4c39-8778-48d66b6a42bd.png)

#### 960x540
![960x540](https://user-images.githubusercontent.com/26721650/177040359-9125b623-59a1-4ef3-90dd-b665145180d3.png)

**Comment by codecat** [comment]
Another option is to require a game restart to change the scaling, then all fonts loaded can receive a scale amount. That should probably have some reasonable limit though, like 200% maximum.

**Comment by codecat** [comment]
I have now implemented this (requiring game restarts) for the next update. Some plugins might need to update their code in order to display properly, which I hope many plugin devs will start doing over time. Here's a screenshot from [the Discord thread](https://discord.com/channels/276076890714800129/1102216235749474314) where I gave developers a headsup about this upcoming feature:

![image](https://user-images.githubusercontent.com/136534/235521992-89748a44-59c4-4377-9e08-176c039def0a.png)
