### ISSUE TITLE
Developer mode is a thing in Maniaplanet/Turbo

### ISSUE THREAD

**Issue by zai-tm** [openplanet-nl/openplanet-issues#158]
Developer Mode should be removed on the ManiaPlanet/Turbo versions of Openplanet because signed plugins don't exist for those versions.

**Comment by codecat** [comment]
The idea behind developer mode is that servers can decide whether or not to allow untrusted plugins, so this would potentially also benefit Maniaplanet. This would make signed plugins useful on Maniaplanet as well.

I do agree that it's not useful for Turbo though, because there are no dedicated servers there.

**Comment by zai-tm** [comment]
Yes but in maniaplanet developer mode disables all plugins that don't come with openplanet

**Comment by codecat** [comment]
I'm sure there are a couple, which would indeed have to be updated to be signed. Which ones are you using that are not signed? We can reach out to those plugin developers to get them updated.

**Comment by codecat** [comment]
Will close this for now. Let me know if this is still super critical.
