### ISSUE TITLE
Inconsistent MemoryBuffer Write Method Behavior

### ISSUE THREAD

**Issue by chipsTM** [openplanet-nl/openplanet-issues#175]
I think through several discussions on discord we talked about `Write()` methods auto seeking the cursor in the buffer. However I'm not seeing this behavior consistently across `MemoryBuffer` write methods.

```
// Generate Random Key
MemoryBuffer nonce = MemoryBuffer(16);
for (uint8 i = 0; i < 16; i++) {
    // print(Math::Rand(0, 256));
    nonce.Seek(i); // try with/without
    nonce.Write(i+1);
    print(i+1);
}
nonce.Seek(0);
string key = nonce.ReadToBase64(16);
print(key);
print("AQIDBAUGBwgJCgsMDQ4PEC=="); // expected value
// although we get AQIDBAUGBwgJCgsMDQ4PEA== instead...maybe expected value is "wrong" (I also verified in a different language too)
```

**Comment by codecat** [comment]
This doesn't actually indicate a bug in MemoryBuffer, but rather a problem/issue/difference in the base64 implementation. Take a look at your decoded data of your "expected" and actual base64 strings, for example:

While `AQIDBAUGBwgJCgsMDQ4PEC==` and `AQIDBAUGBwgJCgsMDQ4PEA==` are 2 different strings, they decode to the same expected data:
```
Nimbletop ~ » printf "AQIDBAUGBwgJCgsMDQ4PEC==" | base64 -d | hexdump -C
00000000  01 02 03 04 05 06 07 08  09 0a 0b 0c 0d 0e 0f 10  |................|

Nimbletop ~ » printf "AQIDBAUGBwgJCgsMDQ4PEA==" | base64 -d | hexdump -C
00000000  01 02 03 04 05 06 07 08  09 0a 0b 0c 0d 0e 0f 10  |................|
```

In fact, only the first 2 bits of the last characters (`C` and `A`) seem to be used. I did not write the base64 implementation used in Openplanet (it's a small library) so I cannot tell if the implementation is objectively wrong or not. In my view, having `A` at the end makes sense since that makes all the bits 0, which is likely what's intended here anyway.

**Comment by chipsTM** [comment]
Sorry I didn't mean to add confusion, I meant the last comment as an aside since it is a base64 topic. 
I still am referring to the `Seek()` behavior where I mention `nonce.Seek(i); // try with/without`

**Comment by codecat** [comment]
So what are the actual results for you if it's not related to the last comment? `Write()` does move the cursor position, so I'm not sure what the actual difference is.

**Comment by chipsTM** [comment]
So without the Seek I get `AQAAAAIAAAADAAAABAAAAA==` 
decodes to 
 0x01 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x03 0x00 0x00 0x00 0x04 0x00 0x00 0x00

I guess this is more about developer best practice. I can fix this by explicitly casting to a `uint8` 
`nonce.Write(uint8(i+1));` 

I guess `i+1` gets interpreted as uint32 by the compiler and I assumed it would respect `i` type 😕

**Comment by codecat** [comment]
Ah yes, that would do it 😅 I guess it upgraded the type because of the right-hand side `1` being a 32 bit integer. Perhaps doing `i + uint8(1)` would work as well.
