### ISSUE TITLE
10s faster start times with openplanet through steam compared to ubi connect

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#269]
See discord conversation about it from feb 13th: https://discord.com/channels/276076890714800129/449983875586850827/1074630681000411227

**Comment by codecat** [comment]
I've added a small little performance trace log so I can debug this. Will report back on the results.

And just to confirm; you didn't make any changes to your game's `Openplanet` folder? (The user dir is fine, I'm wondering about the game's folder)

**Comment by codecat** [comment]
My initial test shows that initialization time isn't spent in Openplanet, but outside of the initialization routines:

![image](https://user-images.githubusercontent.com/136534/218797246-7f355b94-563d-414a-bd94-1e9100a2982d.png)

In the table above, the time marked red is the big difference in initialization timing on my machine. It's faster during game initialization, rather than Openplanet initialization. (`Platform::Initialize` gets called on the first tick of the game update when it's possible.)

I might dig into this more later. Lemme know if you have any additional details.

**Comment by XertroV** [comment]
> And just to confirm; you didn't make any changes to your game's Openplanet folder? (The user dir is fine, I'm wondering about the game's folder)

No -- if I did it would have been a long time ago (many updates ago). The only thing to come to mind is my work on plugin manager from like 6 months ago (can't remember if it required replacing that or not).

I will try deleting it and reinstalling openplanet.

**Comment by XertroV** [comment]
One thing i've noticed: I think loading fonts is faster in the steam version. 

Here's my laggy plugins alerts on startup (I think this is mostly fonts): 
![image](https://user-images.githubusercontent.com/1046448/219285509-2179abdc-4dd2-4c32-ac05-cfc8fd412196.png)

Bingo's hangs are closer to 1s on the ubi version.

**Comment by XertroV** [comment]
TM via uplay: (The better loading screen 12s thing is not typical, fyi, usually more like 5s thru ubi from memory)
![image](https://user-images.githubusercontent.com/1046448/219294801-79db9677-aa04-4f6b-910e-8c61b2368467.png)

**Comment by codecat** [comment]
This sounds like loading textures is faster on Steam then 🤔

**Comment by XertroV** [comment]
> This sounds like loading textures is faster on Steam then 🤔

Yeah, I think both textures and fonts. AFAIK skid marks manager doesn't use a custom font, but does have a big image-heading thing. The others in the picture all use custom fonts.

**Comment by codecat** [comment]
Will close this as a Steam optimization thing. I'm not sure what's happening, but I'm also not sure we can bring these optimizations to Uplay unfortunately.
