### ISSUE TITLE
crash in nod explorer viewing Clips_North

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#303]
replication:
- open editor in new map
- place a block (tested: RoadTechStraight, first block in editor; and the pillar block under that block when placed in normal block mode)
- explore the CGameCtnBlock nod for that block
- expand `BlockUnitsE[0].BlockUnitModel.Clips_North`
- crash

![image](https://user-images.githubusercontent.com/1046448/234443659-bb9795fb-3886-4f48-9efd-457aaf7e13a4.png)

**Comment by codecat** [comment]
I fixed a bug that caused some of these to misbehave, but the actual misbehaving array is the `Clips` array. Accessing it will cause a crash because the buffer pointer is null while the length is 4. This could indicate a Nadeo bug but it could also be something I'm not doing correctly.

It's worth noting that the array is a virtual read property rather than a direct read, so it's likely a "problem" on Nadeo's side. (Problem is in quotes because it might not affect them at all)

**Comment by codecat** [comment]
I'll close this until there's evidence to confirm it as an Openplanet issue.
