### ISSUE TITLE
Request: add `signed` flag to plugin authentication API

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#335]
It would be nice if plugin authentication included a flag for whether the authenticating plugin is signed or not. ATM AFAIK, someone can copy a plugin, modify the code, keep the same site ID, and then authenticate to that plugin's API. Ofc, such a plugin would be unsigned, so it'd be nice if the API could respond differently in some cases.

This issue might largely be mitigated with learning mode, but that wouldn't fix a hacked bingo client for example (unless the bingo server implements some kind of leaderboard / ghost validation)

**Comment by codecat** [comment]
We've briefly discussed this on Discord, but I'll summarize what my thoughts are on this a bit:

I don't think this is a good idea to add, because this information **can never be verified**. (For example, a custom client could do its own authentication against the Openplanet API and pretend that the plugin is signed, while still correctly verifying the user is who they say they are.)

Even if you take into account that this information can be faked, it would be inconsistent with the rest of the API, as the purpose of it is for a third party server to verify a user is who they claim to be, which is (as of writing) guaranteed. This guarantee can never be made for a client-side constraint like a plugin's verification status.

Will close this issue for now, but feel free to put any more thoughts or ideas in this issue.
