### ISSUE TITLE
Audio buzzing after spamming playing a ding

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#418]
I was testing a ding for a timer plugin and spammed the "play ding" button a bunch. I then got an annoying buzzing. reloading the plugin didn't fix. reducing Gain under openplanet audio settings did affect it. game volume did not. required restarting TM to get rid of it.

[timers-1705198503.zip](https://github.com/openplanet-nl/issues/files/13930121/timers-1705198503.zip)

**Comment by codecat** [comment]
This is because you are loading the sample with streaming enabled, which only supports a single voice. I have fixed this problem by not playing any new voices for streamed samples when there is already a voice. If you want to play a single sample with multiple voices, you should keep the sample in memory instead of streaming it. (eg. pass `false` to the second parameter of `Audio::LoadSample`)
